### ISSUE TITLE
"go get" works but package not shown in import

### ISSUE THREAD

**Issue by rotoshniwal** [sspinc/terraform-provider-credstash#10]
I am trying to use this package in my go code : https://github.com/sspinc/terraform-provider-credstash. For doing so, I tried getting the package to my GOPATH using the below command as mentioned in your README as well  :

`$ go get -v -u github.com/sspinc/terraform-provider-credstash`

The above command downloaded the package successfully under my GOPATH as shown below :

`/Users/rohitt/go/src/github.com/sspinc/terraform-provider-credstash`

When I try to import this package now in my go file, it does not suggest this package at all during import. I am not sure why this issue is happening. My GOROOT and GOPATH are correctly set as shown below :

```
rohitt@Dexters-MacBook-Pro ~ $ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rohitt/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rohitt/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64"
```

Is this repo setup for using **go get** ?  Or is there some other problem I am missing ?  Please assist.

**Comment by tmichel** [comment]
terraform-provider-credstash is a binary. Go does not allow you to import main packages. You could import the `credstash` sub-package in this repository if needed. Also when you go get this repo you get a terraform-provider-credstash binary in $GOPATH/bin.
