### ISSUE TITLE
Package license file?

### ISSUE THREAD

**Issue by oblute** [sspinc/terraform-provider-credstash#21]
This repo is missing a license - can this be packaged? Thanks!

**Comment by tmichel** [comment]
I reached out internally a few days ago and I'm waiting on a response. I'll let you know if something comes back.

**Comment by tmichel** [comment]
https://github.com/sspinc/terraform-provider-credstash/commit/b2efd0826001685fec1a1a6a2ab73c5fbd26fc10 adds a license file. We are using MIT so go ahead and package this. 

Sorry this took so long.
