### ISSUE TITLE
Needs to be rebuilt to work with newer versions of terraform 

### ISSUE THREAD

**Issue by beneshed** [sspinc/terraform-provider-credstash#4]
* provider.credstash: Incompatible API version with plugin. Plugin version: 2, Ours: 4

**Comment by tmichel** [comment]
Which Terraform version are you on? It works for me <= 0.8.8.

**Comment by MrPink** [comment]
I'm also having the same issue, using the latest release `Terraform v0.9.1`

**Comment by MrPink** [comment]
I can confirm building against `v0.9.1` fixes the issue

**Comment by MrPink** [comment]
so I built it against the `v0.9.1` release and it works fine just FYI, not sure about backwards compatibility though.

**Comment by tmichel** [comment]
@MrPink Thanks for digging into this. I'll release a new version soon that is compiled against terraform 0.9+.

**Comment by MrPink** [comment]
@tmichel no worries, let me know if I can help further

**Comment by tmichel** [comment]
I have released a new version and pushed the binaries to Github.
Tested it against terraform 0.9.2.
