### ISSUE TITLE
Any reason not to submit this into Terraform?

### ISSUE THREAD

**Issue by evanstachowiak** [sspinc/terraform-provider-credstash#5]
Cool project! Any way to get this merged into Terraform itself so a separate binary isn't necessary?

**Comment by tmichel** [comment]
Honestly I have not thought about it at all. 

[Now that providers are being cut out](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/) of the main terraform repository and every provider gets its own repository it makes a lot of sense to try to get a repo under the Terraform Providers GitHub organization. I will look into that when the migration is over. 

Also I believe with the new structure installing a third-party provider might get easier so you don't have to install the binary manually.
